export const feedData = [
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "5 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 2 Occupancy ",
    summarySubheader: "10 people",
    summaryDate: "2 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "6 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "7 people",
    summaryDate: "1 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "5 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 2 Occupancy ",
    summarySubheader: "10 people",
    summaryDate: "2 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "6 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "7 people",
    summaryDate: "1 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "5 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 2 Occupancy ",
    summarySubheader: "10 people",
    summaryDate: "2 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "6 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "7 people",
    summaryDate: "1 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "5 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 2 Occupancy ",
    summarySubheader: "10 people",
    summaryDate: "2 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "6 people",
    summaryDate: "5 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
  {
    summaryHeader: "Zone 1 Occupancy ",
    summarySubheader: "7 people",
    summaryDate: "1 minutes ago",
    icon: undefined,
    metaHeader: "Camera ID: A5S7GB-UBC",
  },
];
